name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout"
        uses: actions/checkout@v1

      - name: Publish action
        uses: dylanvann/publish-github-action@v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}